cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    rowan.melrose@bisalloy.com.au:
      email: rowan.melrose@bisalloy.com.au
      name: Rowan Melrose
      password: $2b$12$3bDi1T.MB/q8y5TIhVbijupsEuO9QWFt3DsgB9xxZLOHvyPwDYwu2
    wei.chen02@xjtlu.edu.cn:
      email: wei.chen02@xjtlu.edu.cn
      name: Wei Chen
      password: $2b$12$AlADSwlyMzXoY68A744ILeSTQjrdbP.pq4q0dvGNecg92HjynFfxO
    charles.curry@bisalloy.com.au:
      email: charles.curry@bisalloy.com.au
      name: Charles Curry
      password: $2b$12$iXrS1tN3Kx47KurWy7Mh2uE0oHyxxYhfj.Ht/yJ6lgU2IBSLDTz6q
    dxx052@163.com:
      email: dxx052@163.com
      name: Xiangxian Deng
      password: $2b$12$h/gNA02sQmXcSn1H7lcYJeMT/eislNHTvbjC/z18ePwNdK/YY77Da
    bruce.rattray@growthsteel.com:
      email: bruce.rattray@growthsteel.com
      name: Bruce Rattray
      password: $2b$12$66SnxkwJrQsuIqyiM6GyvecPSmtUx7YoIPvhjC87PK1XNIBCFH8Ye
    c.swanepoel@growthsteel.com:
      email: c.swanepoel@growthsteel.com
      name: Craig Swanepoel
      password: $2b$12$tNhEMLiy6O5NCmrVOTc83OUpE2f5NgyEWjvfqqugr/QoCAYvLb6qe          
preauthorized:
  emails:
  - wei.chen@bisalloy.com.au
